package com.projetopi.prove3dapp.telas;

import com.projetopi.prove3dapp.Config;
import com.projetopi.prove3dapp.dadosClasses.Cpu;
import com.projetopi.prove3dapp.dadosClasses.Disco;
import com.projetopi.prove3dapp.dadosClasses.Memoria;
import com.projetopi.prove3dapp.tabelas.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Timer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.util.FormatUtil;

/**
 *
 * @author NOSA201906
 */
@Component
public class TelaEstatisticas extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstatisticas
     */
    public TelaEstatisticas() {
        initComponents();
    }

    TabelaUsuario idUsuario;
    TabelaComputador idComputador;

    @Autowired
    Config config;

    @Autowired
    Cpu cpu;

    @Autowired
    Disco disco;

    @Autowired
    Memoria memoria;

    /*Criando uma instancia de Tempo no java. Essa instância irá chamar o
    método 'ChamarRelogio()' a cada cinco segundos*/
    Timer timer = new Timer(5000, new ChamarRelogio());

    SystemInfo si;
    HardwareAbstractionLayer hal;

    public void pegaCpu() {

        TabelaCpu dadosCpu = new TabelaCpu();

        cpu.pegaCpu(dadosCpu, false, idComputador);

        try {
            si = config.oshi();
            String atividade = dadosCpu.getTempAtividade().toString().split(" ")[3];
            lblCpuModelo.setText(dadosCpu.getModelo());
            lblCpuProcessos.setText(dadosCpu.getProcessos().toString());
            lblCpuTemp.setText(dadosCpu.getTemperatura() + " C");
            lblCpuUtilizacao.setText(String.format("%.2f %%", dadosCpu.getUtilizacao()));
            lblCpuVolt.setText(dadosCpu.getVoltagem() + " V");
            lblCpuAtividade.setText(atividade);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Aqui mesmo");
        }
    }

    public void pegaMemoria() {

        TabelaMemoria dadosMemoria = new TabelaMemoria();
        List<String> data = new ArrayList<>();
        
        memoria.pegaMemoria(dadosMemoria, false, idComputador, data);
        HardwareAbstractionLayer hal = si.getHardware();
        
        lblMemoriaDisponivel.setText(data.get(0));
        lblMemoriaCache.setText(data.get(1));
        lblMemoriaUso.setText(data.get(2));
        lblMemoriaModelo.setText(data.get(0));

    }

    public void pegaDisco() {

        TabelaDisco dadosDisco = new TabelaDisco();
        List<String> data = new ArrayList<>();

        disco.pegaDisco(dadosDisco, false, idComputador, data);

        lblDiscoModelo.setText(dadosDisco.getModelo());
        lblDiscoVLeitura.setText(data.get(0));
        lblDiscoVGravacao.setText(data.get(1));
    }

    public void dados() {
        pegaCpu();
        pegaDisco();
        pegaMemoria();
    }

    public void disparaRelogio() {
        // Inicia o timer, para que a cada 5 seg, ele se repita
        timer.start();
    }

    class ChamarRelogio implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            //Chamando o método que irá pegar os processos do sistema
            dados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpCPU = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblCpuProcessos = new javax.swing.JLabel();
        lblCpuTemp = new javax.swing.JLabel();
        lblCpuVolt = new javax.swing.JLabel();
        lblCpuAtividade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCpuUtilizacao = new javax.swing.JLabel();
        lblCpuModelo = new javax.swing.JLabel();
        jpDisco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDiscoModelo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDiscoVLeitura = new javax.swing.JLabel();
        lblDiscoVGravacao = new javax.swing.JLabel();
        lblDiscoAtividade = new javax.swing.JLabel();
        lblDiscoTempResp = new javax.swing.JLabel();
        jpMemoria = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        lblMemoriaModelo = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblMemoriaUso = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        lblMemoriaConfirm = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lblMemoriaCache = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        lblMemoriaDisponivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatísticas");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel5.setText("CPU:");

        jLabel12.setText("Processos: ");

        jLabel13.setText("Temperatura:");

        jLabel14.setText("Voltagem:");

        jLabel17.setText("Tempo de Atividade:");

        jLabel2.setText("Utilização");

        lblCpuModelo.setText("Coletando dados CPU...");

        javax.swing.GroupLayout jpCPULayout = new javax.swing.GroupLayout(jpCPU);
        jpCPU.setLayout(jpCPULayout);
        jpCPULayout.setHorizontalGroup(
            jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCPULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jpCPULayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpuProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCpuTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel2)
                                    .addGroup(jpCPULayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCpuAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCpuUtilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(64, 64, 64))
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(jpCPULayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblCpuVolt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpCPULayout.setVerticalGroup(
            jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCPULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpuModelo))
                .addGap(18, 18, 18)
                .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCPULayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuUtilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCpuVolt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CPU", jpCPU);

        jLabel1.setText("Disco:");

        lblDiscoModelo.setText("Coletando dados disco...");

        jLabel3.setText("Velocidade de Leitura:");

        jLabel4.setText("Velocidade de Gravação:");

        jLabel6.setText("Tempo de Atividade:");

        jLabel7.setText("Tempo de Resposta: ");

        javax.swing.GroupLayout jpDiscoLayout = new javax.swing.GroupLayout(jpDisco);
        jpDisco.setLayout(jpDiscoLayout);
        jpDiscoLayout.setHorizontalGroup(
            jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDiscoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDiscoModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpDiscoLayout.createSequentialGroup()
                        .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jpDiscoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiscoVGravacao)
                                    .addComponent(lblDiscoVLeitura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(83, 83, 83)
                        .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jpDiscoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDiscoAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(lblDiscoTempResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jpDiscoLayout.setVerticalGroup(
            jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoAtividade)
                    .addComponent(lblDiscoVLeitura))
                .addGap(18, 18, 18)
                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoTempResp)
                    .addComponent(lblDiscoVGravacao))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Disco", jpDisco);

        jLabel40.setText("Memória:");

        lblMemoriaModelo.setText("Coletando dados memória...");

        jLabel43.setText("Em Uso:");

        jLabel47.setText("Confirmado:");

        jLabel49.setText("Cache:");

        jLabel55.setText("Disponível:");

        javax.swing.GroupLayout jpMemoriaLayout = new javax.swing.GroupLayout(jpMemoria);
        jpMemoria.setLayout(jpMemoriaLayout);
        jpMemoriaLayout.setHorizontalGroup(
            jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMemoriaLayout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMemoriaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpMemoriaLayout.createSequentialGroup()
                        .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel49)
                            .addGroup(jpMemoriaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMemoriaUso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMemoriaCache, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel55)
                            .addGroup(jpMemoriaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMemoriaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMemoriaDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(89, 89, 89))))
        );
        jpMemoriaLayout.setVerticalGroup(
            jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMemoriaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMemoriaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMemoriaUso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemoriaCache, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMemoriaDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(313, 313, 313))
        );

        jTabbedPane1.addTab("Memória", jpMemoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        timer.stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstatisticas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpCPU;
    private javax.swing.JPanel jpDisco;
    private javax.swing.JPanel jpMemoria;
    private javax.swing.JLabel lblCpuAtividade;
    private javax.swing.JLabel lblCpuModelo;
    private javax.swing.JLabel lblCpuProcessos;
    private javax.swing.JLabel lblCpuTemp;
    private javax.swing.JLabel lblCpuUtilizacao;
    private javax.swing.JLabel lblCpuVolt;
    private javax.swing.JLabel lblDiscoAtividade;
    private javax.swing.JLabel lblDiscoModelo;
    private javax.swing.JLabel lblDiscoTempResp;
    private javax.swing.JLabel lblDiscoVGravacao;
    private javax.swing.JLabel lblDiscoVLeitura;
    private javax.swing.JLabel lblMemoriaCache;
    private javax.swing.JLabel lblMemoriaConfirm;
    private javax.swing.JLabel lblMemoriaDisponivel;
    private javax.swing.JLabel lblMemoriaModelo;
    private javax.swing.JLabel lblMemoriaUso;
    // End of variables declaration//GEN-END:variables
}
